name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        # env:
        #   ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        #   ECR_REPOSITORY: ecs-next-app
        #   IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ecs-next-app .
          docker tag ecs-next-app:latest 397491111170.dkr.ecr.us-east-1.amazonaws.com/ecs-next-app:latest
          docker push 397491111170.dkr.ecr.us-east-1.amazonaws.com/ecs-next-app:latest

      - name: Deploy to Amazon ECS
        run: |
          aws ecs update-service --cluster next-app-cluster --service next-app-service --force-new-deployment
